site_name: MiniLisp++
site_description: Notas del laboratorio de Lenguajes de Programación 2027-1
site_author: Leslie SanV

theme: 
  name: readthedocs
  language: es


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Inicio: index.md
  - Práctica 01:
    - Introducción a Haskell: lab01/haskell.md
    - Retos de la semana: lab01/retos.md 
    - Ejecución de pruebas: lab01/pruebas.md 
  - Práctica 02:
    - Análisis léxico y sintáctico: lab02/intro.md
    - Retos de la semana: lab02/retos.md 
    - Ejecución de pruebas: lab02/pruebas.md
  - Práctica 03:
    - Integración de la semántica: lab03/intro.md
    - Retos de la semana: lab03/retos.md
    - Intérprete de MiniLisp++: lab03/minilisp.md
    - Ejecución de pruebas: lab03/pruebas.md
#  - Práctica 04:
#    - Evaluación funcional: lab04/intro.md
#    - Retos de la semana: lab04/retos.md 
#    - Intérprete de MiniLisp++: lab04/minilisp.md
#    - Ejecución de pruebas: lab04/pruebas.md
#  - Práctica 05:
#    - Estrategias de evaluación y recursión: lab05/intro.md
#    - Retos de la semana: lab05/retos.md 
#    - Ejecución de pruebas: lab05/pruebas.md
#  - Práctica 06:
#    - CPS y recursión de cola: lab06/intro.md 
#    - Retos de la semana: lab06/retos.md 
#    - Ejecución de pruebas: lab06/pruebas.md
